services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8010:8010"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
